City-of-Helsinki/ahti

.pre-commit-config.yaml
README.md

This PR lists all code formatting and quality checking tools used (in Travis) in the README. For convenience a [`pre-commit`](https://pre-commit.com/) configuration is also included to automatically run the tools as git hooks when making a commit.

Include code formatting tools

---

.gitlab-ci.yml

This PR will make sure features are imported when deploying the container.

Import features automatically on deploy

---

features/schema.py
features/tests/factories.py
features/tests/snapshots/snap_test_api.py
features/tests/test_api.py
features/tests/test_models.py

This PR add images to the features GraphQL API.

AHTI-113 Serve feature images from GQL API

---

features/importers/myhelsinki_places/importer.py
features/importers/myhelsinki_places/tests/conftest.py

Adds location+distance based filter to MyHelsinki mapping config
Refs AHTI-193

AHTI-193 | Multiple calls to MyHelsinki API using different query parameters

---

features/schema.py

This PR reduces the amount of queries when resolving features.
Refs AHTI-44

AHTI-44 | Optimize queries for resolving Features

---

requirements-dev.txt
requirements.txt

This PR bumps libraries used by the project. Some libraries have added e.g. official Python 3.8 support.

Bump requirements

---

features/models.py
features/schema.py
features/tests/snapshots/snap_test_api.py
features/tests/test_api.py
features/tests/test_models.py

This PR adds a query for a single feature. It takes either `id` or `ahtiId` as an argument.

AHTI-223 | Add GQL query for a single feature

---

features/schema.py
features/tests/test_api_filtering.py

If there would be more than one override distinct would be required.
Refs AHTI-223

AHTI-223 | Make updatedSince feature filter query use distinct

---

features/admin.py
features/models.py

This PR adds initial django-admin interface for managing features.

AHTI-172 | Manage Features in Django admin

---

ahti/settings.py
features/importers/myhelsinki_places/importer.py
features/importers/myhelsinki_places/tests/test_import_features.py
features/importers/myhelsinki_places/tests/test_import_images.py
features/importers/venepaikka_harbors/__init__.py
features/importers/venepaikka_harbors/app_settings.py
features/importers/venepaikka_harbors/apps.py
features/importers/venepaikka_harbors/config.json
features/importers/venepaikka_harbors/importer.py
features/importers/venepaikka_harbors/tests/conftest.py
features/importers/venepaikka_harbors/tests/responses/harbors_response.json
features/importers/venepaikka_harbors/tests/test_import_categories.py
features/importers/venepaikka_harbors/tests/test_import_contact_info.py
features/importers/venepaikka_harbors/tests/test_import_harbors.py
features/importers/venepaikka_harbors/tests/test_import_images.py
features/importers/venepaikka_harbors/tests/test_import_tags.py
features/management/commands/import_features.py
features/tests/snapshots/snap_test_api.py
features/tests/test_api.py
features/tests/test_importers.py

This PR adds venepaikka harbour data importer. Harbours are imported as Features without any harbour specific data.

AHTI-202 AHTI-203 | Import harbors from venepaikka

---

categories/admin.py
features/admin.py

This PR adds minor optimizations to the django-admin views to reduce the amount of queries.

Optimize django-admin queries

---

features/importers/myhelsinki_places/importer.py
features/importers/venepaikka_harbors/importer.py

If there are any changes in the imported data, it should get saved into the DB.

Use update_or_create instead of get_or_create in importers

---

features/admin.py

the goal of this PR is to enable bulk editing of feature visibility in the django admin.

add bulk editing of feature visibility, AHTI-391

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

This PR adds the recommended PR and issue templates.

AHTI-331 | Add GitHub PR and issue templates

---

CONTRIBUTING.md
README.md

Update the project README to conform with documentation practices.
Refs AHTI-331, AHTI-412

AHTI-412 | Update project information on README

---

features/schema.py
features/tests/snapshots/snap_test_api.py
features/tests/test_api.py
features/tests/test_models.py
requirements-dev.txt
requirements.txt

This PR fixes an issue noticed while documenting the API. PriceTag instances were not available from the API.
**[AHTI-331](https://helsinkisolutionoffice.atlassian.net/browse/AHTI-331):** Technical documentation

AHTI-331 | Fix PriceTags not available in the API

---

.gitlab-ci.yml
.prod/on_deploy.sh
Dockerfile
docker-compose.yml
docker-entrypoint.sh
features/admin.py
requirements.in
requirements.txt

This code should enable the production environment to restore/reset the DB to a state of the provided database dump. Magic wormhole will be used for delivering the DB dump to the image from a developer machine.
**[AHTI-419](https://helsinkisolutionoffice.atlassian.net/browse/AHTI-419):** BE: Migrate data from staging (QA) to production

AHTI-419 | Reset database to a DB dump

---

CONTRIBUTING.md

AHTI-415 | Add contact information to contribution guidelines

---

features/importers/myhelsinki_places/importer.py
features/importers/venepaikka_harbors/importer.py

This PR increases the timeout values on importers. Increase so that the time it takes and timeout value are not so close to each other.

Increase timeouts of importer calls

---

.github/workflows/on_pull_request.yml
.github/workflows/production.yml
.github/workflows/staging.yml
.github/workflows/stop_review.yml

**[AHTI-XXX](https://helsinkisolutionoffice.atlassian.net/browse/AHTI-XXX):**

Use Github Actions for CI/CD instead of Gitlab

---

.github/workflows/production.yml
.github/workflows/review.yml

**[AHTI-XXX](https://helsinkisolutionoffice.atlassian.net/browse/AHTI-XXX):**

Fix a typo in GA workflow

---

.github/workflows/production.yml

**[AHTI-XXX](https://helsinkisolutionoffice.atlassian.net/browse/AHTI-XXX):**

Add additional_hostnames block
